### content configuration ###
name: Filipe Luiz
job: Desenvolvedor Front-End 
title: Filipe Luiz - Desenvolvedor Front-End
description: Um portfolio de um desenvolvedor Front-End, Surdo e apaixonado por novas tecnologias.
email: ffilipeluiz@gmail.com
url: "https://filipeluiz.com.br/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_username: https://plus.google.com/116973113303020587442/
keywords: Filipe Luiz surdo, desenvolvimento web surdo, desenvolvedor surdo, Front-End surdo, HTML5 surdo, CSS3 surdo, JavaScript surdo

social:
  - name: twitter
    title: Veja no meu twitter
    url: https://twitter.com/filipelluiz
  - name: github
    title: Veja o meu código no github
    url: https://github.com/filipeluiz
  - name: linkedin2
    title: Veja do meu curriculo no linkedin
    url: https://www.linkedin.com/in/ffilipeluiz

### site serving configuration ###
exclude: ['package.json', 'src', 'node_modules', '.sass-cache']
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids:  false


